### ISSUE TITLE
Support pseudo classes without selector

### ISSUE THREAD

**Issue by Brixy** [Mnwa/css-minify#1]
Hi,

yesterday I raised [this issue](https://github.com/wilsonzlin/minify-html/issues/110).

It seems that `css-minify` is causing the problem:

It should be possibe to use a pseudo class without a selector, e.g. `:is()` instead of `*:is()`.

```
/* Original CSS (without `*` selector) */
:is(nav, .posts) a {
	text-decoration: none;
}
```

```
/* Minified CSS (error) */
:is(nav{text-decoration:none}
```

```
/* Original CSS (with `*` selector) */
:is(nav, .posts) a {
	text-decoration: none;
}
```

```
/* Minified CSS (correct) */
*:is(nav,.posts) a{text-decoration:none}
```

Thank you very much!

**Comment by Mnwa** [comment]
Hey! I will try to check it soon.

**Comment by Mnwa** [comment]
I added adhoc support on 0.3.1 version

**Comment by Brixy** [comment]
Excellent. Thanks a lot for your efforts.
