### ISSUE TITLE
incorrect optimization for `font` attribute

### ISSUE THREAD

**Issue by flumm** [Mnwa/css-minify#13]
Hi,

having 

```
.class {
    font: normal normal normal  14px/3 Arial;
}
```
as the input. With 'non dangerous optimizations' (e.g. when using https://css-minify.panfilov.tech/) 
it gets optimized to:

```
.class{font:400 400 400  14px/3 Arial}
```

which is wrong.  (It does not work in chromium at least).

See https://developer.mozilla.org/en-US/docs/Web/CSS/font on what can be used here. (only the third option `font-weight` can be replaced by `400` not `font-style` (the first parameter) or `font-variant` the second parameter.

**Comment by Mnwa** [comment]
Hello! Thanks for you issue, now this optimization accepting only `font-weight` perameters
