### ISSUE TITLE
panic on invalid color value

### ISSUE THREAD

**Issue by SArpnt** [Mnwa/css-minify#9]
```rs
use css_minify::optimizations::{Minifier, Level};
fn main() {
	let _ = std::hint::black_box(
		Minifier::default().minify("*{color:#f}", Level::Three)
	);
}
```
```
thread 'main' panicked at 'byte index 4 is out of bounds of `#f`', /home/sarpnt/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/css-minify-0.3.1/src/optimizations/color.rs:27:12
```

issue is [here](https://github.com/Mnwa/css-minify/blob/1eab43512108dcafa4bbd33289369adeea8eba3d/css-minify/src/optimizations/color.rs#L25), you should instead use [get](https://doc.rust-lang.org/std/primitive.str.html#method.get) which doesn't panic. you might want to check other cases of indexing in your code too and ensure they don't have a chance of panicking either.

**Comment by Mnwa** [comment]
Hi! Thanks for you issue. Now it fixed
